name:                scihask
version:             0.1.0.0
github:              "folivetti/SciHask"
license:             BSD3
author:              "Fabricio Olivetti de Franca"
maintainer:          "fabricio.olivetti@gmail.com"
copyright:           "2023 Fabricio Olivetti de Franca"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/folivetti/SciHask#readme>

dependencies:
- base >= 4.7 && < 5
- random
- hmatrix
- hmatrix-gsl
- massiv
- criterion
- deepseq
- scheduler 
- containers 
- mtl 

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  scihask:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optc-O2
    - -fforce-recomp
    dependencies:
    - scihask

tests:
  scihask-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scihask
